package com.hurenjieee.entity;
// Generated 2017-3-6 18:59:56 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin",catalog = "strms")
public class Admin implements java.io.Serializable {

    private long   admId;
    private String admName;
    private String admPassword;
    private String admPicture;

    public Admin() {}

    public Admin(long admId) {
        this.admId = admId;
    }

    public Admin(long admId, String admName, String admPassword, String admPicture) {
        this.admId = admId;
        this.admName = admName;
        this.admPassword = admPassword;
        this.admPicture = admPicture;
    }

    @Id

    @Column(name = "adm_id",unique = true,nullable = false)
    public long getAdmId(){
        return this.admId;
    }

    public void setAdmId(long admId){
        this.admId = admId;
    }

    @Column(name = "adm_name",length = 16)
    public String getAdmName(){
        return this.admName;
    }

    public void setAdmName(String admName){
        this.admName = admName;
    }

    @Column(name = "adm_password",length = 64)
    public String getAdmPassword(){
        return this.admPassword;
    }

    public void setAdmPassword(String admPassword){
        this.admPassword = admPassword;
    }

    @Column(name = "adm_picture",length = 64)
    public String getAdmPicture(){
        return this.admPicture;
    }

    public void setAdmPicture(String admPicture){
        this.admPicture = admPicture;
    }

}
