package com.hurenjieee.entity;
// Generated 2016-12-12 22:04:30 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "strms")
public class Admin implements java.io.Serializable {

	private String admUuid;
	private String admName;
	private String admPassword;
	private Date admCdate;
	private Date admUdate;
	private Boolean admTop;
	private String admPic;

	public Admin() {
	}

	public Admin(String admUuid) {
		this.admUuid = admUuid;
	}

	public Admin(String admUuid, String admName, String admPassword, Date admCdate, Date admUdate, Boolean admTop,
			String admPic) {
		this.admUuid = admUuid;
		this.admName = admName;
		this.admPassword = admPassword;
		this.admCdate = admCdate;
		this.admUdate = admUdate;
		this.admTop = admTop;
		this.admPic = admPic;
	}

	@Id

	@Column(name = "adm_uuid", unique = true, nullable = false, length = 32)
	public String getAdmUuid() {
		return this.admUuid;
	}

	public void setAdmUuid(String admUuid) {
		this.admUuid = admUuid;
	}

	@Column(name = "adm_name", length = 16)
	public String getAdmName() {
		return this.admName;
	}

	public void setAdmName(String admName) {
		this.admName = admName;
	}

	@Column(name = "adm_password", length = 16)
	public String getAdmPassword() {
		return this.admPassword;
	}

	public void setAdmPassword(String admPassword) {
		this.admPassword = admPassword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "adm_cdate", length = 19)
	public Date getAdmCdate() {
		return this.admCdate;
	}

	public void setAdmCdate(Date admCdate) {
		this.admCdate = admCdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "adm_udate", length = 19)
	public Date getAdmUdate() {
		return this.admUdate;
	}

	public void setAdmUdate(Date admUdate) {
		this.admUdate = admUdate;
	}

	@Column(name = "adm_top")
	public Boolean getAdmTop() {
		return this.admTop;
	}

	public void setAdmTop(Boolean admTop) {
		this.admTop = admTop;
	}

	@Column(name = "adm_pic")
	public String getAdmPic() {
		return this.admPic;
	}

	public void setAdmPic(String admPic) {
		this.admPic = admPic;
	}

}
