package com.hurenjieee.entity;
// Generated 2017-3-6 18:59:56 by Hibernate Tools 4.3.5.Final

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name = "branch",catalog = "strms")
public class Branch implements java.io.Serializable {

    private long    braId;
    private String braName;
    private Set<Major> majors;

    public Branch() {}

    public Branch(long braId) {
        this.braId = braId;
    }

    public Branch(long braId, String braName) {
        this.braId = braId;
        this.braName = braName;
    }

    @Id

    @Column(name = "bra_id",unique = true,nullable = false)
    public long getBraId(){
        return this.braId;
    }

    public void setBraId(long braId){
        this.braId = braId;
    }

    @Column(name = "bra_name",length = 32)
    public String getBraName(){
        return this.braName;
    }

    public void setBraName(String braName){
        this.braName = braName;
    }

    @OneToMany(cascade=CascadeType.ALL,mappedBy="majBraId")
    //@OneToMany(cascade=CascadeType.ALL,mappedBy="clazz",fetch=FetchType.EAGER) πÿ±’—”≥Ÿº”‘ÿ°£ 
    public Set<Major> getMajors(){
        return majors;
    }

    
    public void setMajors(Set<Major> majors){
        this.majors = majors;
    }

}
