package com.hurenjieee.entity;
// Generated 2017-3-6 18:59:56 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name = "branch",catalog = "strms")
public class Branch implements java.io.Serializable {

    private int    braId;
    private String braName;

    public Branch() {}

    public Branch(int braId) {
        this.braId = braId;
    }

    public Branch(int braId, String braName) {
        this.braId = braId;
        this.braName = braName;
    }

    @Id

    @Column(name = "bra_id",unique = true,nullable = false)
    public int getBraId(){
        return this.braId;
    }

    public void setBraId(int braId){
        this.braId = braId;
    }

    @Column(name = "bra_name",length = 32)
    public String getBraName(){
        return this.braName;
    }

    public void setBraName(String braName){
        this.braName = braName;
    }

}
