package com.hurenjieee.entity;
// Generated 2016-12-12 22:00:57 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Class generated by hbm2java
 */
@Entity
@Table(name = "class", catalog = "strms")
public class Class implements java.io.Serializable {

	private String classUuid;
	private Branch branch;
	private String className;
	private Integer classYear;
	private Set<Student> students = new HashSet<Student>(0);

	public Class() {
	}

	public Class(String classUuid) {
		this.classUuid = classUuid;
	}

	public Class(String classUuid, Branch branch, String className, Integer classYear, Set<Student> students) {
		this.classUuid = classUuid;
		this.branch = branch;
		this.className = className;
		this.classYear = classYear;
		this.students = students;
	}

	@Id

	@Column(name = "class_uuid", unique = true, nullable = false, length = 32)
	public String getClassUuid() {
		return this.classUuid;
	}

	public void setClassUuid(String classUuid) {
		this.classUuid = classUuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_major_uuid")
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@Column(name = "class_name")
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "class_year")
	public Integer getClassYear() {
		return this.classYear;
	}

	public void setClassYear(Integer classYear) {
		this.classYear = classYear;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "class")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
