package com.hurenjieee.entity;
// Generated 2016-12-12 22:04:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Collective generated by hbm2java
 */
@Entity
@Table(name = "collective", catalog = "strms")
public class Collective implements java.io.Serializable {

	private String colUuid;
	private Branch branch;
	private String colName;
	private Integer colYear;
	private Set<Student> students = new HashSet<Student>(0);

	public Collective() {
	}

	public Collective(String colUuid) {
		this.colUuid = colUuid;
	}

	public Collective(String colUuid, Branch branch, String colName, Integer colYear, Set<Student> students) {
		this.colUuid = colUuid;
		this.branch = branch;
		this.colName = colName;
		this.colYear = colYear;
		this.students = students;
	}

	@Id

	@Column(name = "col_uuid", unique = true, nullable = false, length = 32)
	public String getColUuid() {
		return this.colUuid;
	}

	public void setColUuid(String colUuid) {
		this.colUuid = colUuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "col_major_uuid")
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@Column(name = "col_name")
	public String getColName() {
		return this.colName;
	}

	public void setColName(String colName) {
		this.colName = colName;
	}

	@Column(name = "col_year")
	public Integer getColYear() {
		return this.colYear;
	}

	public void setColYear(Integer colYear) {
		this.colYear = colYear;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "collective")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
