package com.hurenjieee.entity;
// Generated 2016-12-23 22:59:09 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Collective generated by hbm2java
 */
@Entity
@Table(name = "collective", catalog = "strms")
public class Collective implements java.io.Serializable{

	private String colUuid;
	private String colName;
	private Integer colYear;
	private String colMajorUuid;

	public Collective() {
	}

	public Collective(String colUuid) {
		this.colUuid = colUuid;
	}

	public Collective(String colUuid, String colName, Integer colYear, String colMajorUuid) {
		this.colUuid = colUuid;
		this.colName = colName;
		this.colYear = colYear;
		this.colMajorUuid = colMajorUuid;
	}

	@Id

	@GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid.hex")
	@Column(name = "col_uuid", unique = true, nullable = false, length = 32)
	public String getColUuid() {
		return this.colUuid;
	}

	public void setColUuid(String colUuid) {
		this.colUuid = colUuid;
	}

	@Column(name = "col_name")
	public String getColName() {
		return this.colName;
	}

	public void setColName(String colName) {
		this.colName = colName;
	}

	@Column(name = "col_year")
	public Integer getColYear() {
		return this.colYear;
	}

	public void setColYear(Integer colYear) {
		this.colYear = colYear;
	}

	@Column(name = "col_major_uuid", length = 32)
	public String getColMajorUuid() {
		return this.colMajorUuid;
	}

	public void setColMajorUuid(String colMajorUuid) {
		this.colMajorUuid = colMajorUuid;
	}

}
