package com.hurenjieee.entity;
// Generated 2017-4-16 13:20:41 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Formula;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment",catalog = "strms")
public class Comment implements java.io.Serializable {

    private Long   comId;
    private Date   comDate;
    private Long   comRoleId;
    private Integer   comRoleType;
    private String comContent;
    private String comState;
    private Long   comResId;
    private String comRoleName;

    public Comment() {}

    public Comment(Date comDate, Long comRoleId, Integer comRoleType, String comContent, String comState, Long comResId) {
        this.comDate = comDate;
        this.comRoleId = comRoleId;
        this.comRoleType = comRoleType;
        this.comContent = comContent;
        this.comState = comState;
        this.comResId = comResId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "com_id",unique = true,nullable = false)
    public Long getComId(){
        return this.comId;
    }

    public void setComId(Long comId){
        this.comId = comId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "com_date",length = 19)
    public Date getComDate(){
        return this.comDate;
    }

    public void setComDate(Date comDate){
        this.comDate = comDate;
    }

    @Column(name = "com_role_id")
    public Long getComRoleId(){
        return this.comRoleId;
    }

    public void setComRoleId(Long comRoleId){
        this.comRoleId = comRoleId;
    }

    @Column(name = "com_role_type")
    public Integer getComRoleType(){
        return this.comRoleType;
    }

    public void setComRoleType(Integer comRoleType){
        this.comRoleType = comRoleType;
    }

    @Column(name = "com_content",length = 512)
    public String getComContent(){
        return this.comContent;
    }

    public void setComContent(String comContent){
        this.comContent = comContent;
    }

    @Column(name = "com_state",length = 16)
    public String getComState(){
        return this.comState;
    }

    public void setComState(String comState){
        this.comState = comState;
    }

    @Column(name = "com_res_id")
    public Long getComResId(){
        return this.comResId;
    }

    public void setComResId(Long comResId){
        this.comResId = comResId;
    }

    @Formula("case when com_role_type = 1 "
            + "then (select s.stu_name from student s where s.stu_id = com_role_id) "
            + "when com_role_type = 2 "
            + "then (select t.tea_name from teacher t where t.tea_id = com_role_id) "
            + "end") 
    public String getComRoleName(){
        return comRoleName;
    }

    
    public void setComRoleName(String comRoleName){
        this.comRoleName = comRoleName;
    }

}
