package com.hurenjieee.entity;
// Generated 2016-12-9 23:09:58 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dictionary generated by hbm2java
 */
@Entity
@Table(name = "dictionary", catalog = "strms")
public class Dictionary implements java.io.Serializable {

	private String uuidid;
	private String key;
	private String value;

	public Dictionary() {
	}

	public Dictionary(String uuidid) {
		this.uuidid = uuidid;
	}

	public Dictionary(String uuidid, String key, String value) {
		this.uuidid = uuidid;
		this.key = key;
		this.value = value;
	}

	@Id

	@Column(name = "uuidid", unique = true, nullable = false, length = 32)
	public String getUuidid() {
		return this.uuidid;
	}

	public void setUuidid(String uuidid) {
		this.uuidid = uuidid;
	}

	@Column(name = "key")
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
