package com.hurenjieee.entity;
// Generated 2016-12-23 22:59:09 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "log", catalog = "strms")
public class Log implements java.io.Serializable {

	private String logUuid;
	private String logOperaterUuid;
	private String logOperaterType;
	private String logContent;
	private Date logDate;

	public Log() {
	}

	public Log(String logUuid) {
		this.logUuid = logUuid;
	}

	public Log(String logUuid, String logOperaterUuid, String logOperaterType, String logContent, Date logDate) {
		this.logUuid = logUuid;
		this.logOperaterUuid = logOperaterUuid;
		this.logOperaterType = logOperaterType;
		this.logContent = logContent;
		this.logDate = logDate;
	}

	@Id

	@GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid.hex")
	@Column(name = "log_uuid", unique = true, nullable = false, length = 32)
	public String getLogUuid() {
		return this.logUuid;
	}

	public void setLogUuid(String logUuid) {
		this.logUuid = logUuid;
	}

	@Column(name = "log_operater_uuid")
	public String getLogOperaterUuid() {
		return this.logOperaterUuid;
	}

	public void setLogOperaterUuid(String logOperaterUuid) {
		this.logOperaterUuid = logOperaterUuid;
	}

	@Column(name = "log_operater_type")
	public String getLogOperaterType() {
		return this.logOperaterType;
	}

	public void setLogOperaterType(String logOperaterType) {
		this.logOperaterType = logOperaterType;
	}

	@Column(name = "log_content")
	public String getLogContent() {
		return this.logContent;
	}

	public void setLogContent(String logContent) {
		this.logContent = logContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "log_date", length = 19)
	public Date getLogDate() {
		return this.logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

}
