package com.hurenjieee.entity;
// Generated 2016-12-12 22:04:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Major generated by hbm2java
 */
@Entity
@Table(name = "major", catalog = "strms")
public class Major implements java.io.Serializable {

	private String majUuid;
	private Branch branch;
	private String majName;
	private Set<Teacher> teachers = new HashSet<Teacher>(0);

	public Major() {
	}

	public Major(String majUuid) {
		this.majUuid = majUuid;
	}

	public Major(String majUuid, Branch branch, String majName, Set<Teacher> teachers) {
		this.majUuid = majUuid;
		this.branch = branch;
		this.majName = majName;
		this.teachers = teachers;
	}

	@Id

	@Column(name = "maj_uuid", unique = true, nullable = false, length = 32)
	public String getMajUuid() {
		return this.majUuid;
	}

	public void setMajUuid(String majUuid) {
		this.majUuid = majUuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "maj_bra_uuid")
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@Column(name = "maj_name", length = 40)
	public String getMajName() {
		return this.majName;
	}

	public void setMajName(String majName) {
		this.majName = majName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "major")
	public Set<Teacher> getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Set<Teacher> teachers) {
		this.teachers = teachers;
	}

}
