package com.hurenjieee.entity;
// Generated 2017-3-6 18:59:56 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Major generated by hbm2java
 */
@Entity
@Table(name = "major",catalog = "strms")
public class Major implements java.io.Serializable {

    private long   majId;
    private String majName;
    private Long   majBraId;

    public Major() {}

    public Major(long majId) {
        this.majId = majId;
    }

    public Major(long majId, String majName, Long majBraId) {
        this.majId = majId;
        this.majName = majName;
        this.majBraId = majBraId;
    }

    @Id

    @Column(name = "maj_id",unique = true,nullable = false)
    public long getMajId(){
        return this.majId;
    }

    public void setMajId(long majId){
        this.majId = majId;
    }

    @Column(name = "maj_name",length = 32)
    public String getMajName(){
        return this.majName;
    }

    public void setMajName(String majName){
        this.majName = majName;
    }

    @Column(name = "maj_bra_id")
    public Long getMajBraId(){
        return this.majBraId;
    }

    public void setMajBraId(Long majBraId){
        this.majBraId = majBraId;
    }

}
