package com.hurenjieee.entity;
// Generated 2016-12-23 22:59:09 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Major generated by hbm2java
 */
@Entity
@Table(name = "major", catalog = "strms")
public class Major implements java.io.Serializable {

	private String majUuid;
	private String majName;
	private String majBraUuid;

	public Major() {
	}

	public Major(String majUuid) {
		this.majUuid = majUuid;
	}

	public Major(String majUuid, String majName, String majBraUuid) {
		this.majUuid = majUuid;
		this.majName = majName;
		this.majBraUuid = majBraUuid;
	}

	@Id

	@GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid.hex")
	@Column(name = "maj_uuid", unique = true, nullable = false, length = 32)
	public String getMajUuid() {
		return this.majUuid;
	}

	public void setMajUuid(String majUuid) {
		this.majUuid = majUuid;
	}

	@Column(name = "maj_name", length = 40)
	public String getMajName() {
		return this.majName;
	}

	public void setMajName(String majName) {
		this.majName = majName;
	}

	@Column(name = "maj_bra_uuid", length = 20)
	public String getMajBraUuid() {
		return this.majBraUuid;
	}

	public void setMajBraUuid(String majBraUuid) {
		this.majBraUuid = majBraUuid;
	}

}
