package com.hurenjieee.entity;
// Generated 2017-5-8 21:39:59 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Relation generated by hbm2java
 */
@Entity
@Table(name = "relation",catalog = "strms")
public class Relation implements java.io.Serializable {

    private Long reaId;
    private Long reaTeaId;
    private Long reaColId;

    public Relation() {}

    public Relation(Long reaTeaId, Long reaColId) {
        this.reaTeaId = reaTeaId;
        this.reaColId = reaColId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "rea_id",unique = true,nullable = false)
    public Long getReaId(){
        return this.reaId;
    }

    public void setReaId(Long reaId){
        this.reaId = reaId;
    }

    @Column(name = "rea_tea_id")
    public Long getReaTeaId(){
        return this.reaTeaId;
    }

    public void setReaTeaId(Long reaTeaId){
        this.reaTeaId = reaTeaId;
    }

    @Column(name = "rea_col_id")
    public Long getReaColId(){
        return this.reaColId;
    }

    public void setReaColId(Long reaColId){
        this.reaColId = reaColId;
    }

}
