package com.hurenjieee.entity;
// Generated 2017-5-9 21:34:12 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Relation generated by hbm2java
 */
@Entity
@Table(name = "relation",catalog = "strms")
public class Relation implements java.io.Serializable {

    private Long relId;
    private Long relTeaId;
    private Long relColId;

    public Relation() {}

    public Relation(Long relTeaId, Long relColId) {
        this.relTeaId = relTeaId;
        this.relColId = relColId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "rel_id",unique = true,nullable = false)
    public Long getRelId(){
        return this.relId;
    }

    public void setRelId(Long relId){
        this.relId = relId;
    }

    @Column(name = "rel_tea_id")
    public Long getRelTeaId(){
        return this.relTeaId;
    }

    public void setRelTeaId(Long relTeaId){
        this.relTeaId = relTeaId;
    }

    @Column(name = "rel_col_id")
    public Long getRelColId(){
        return this.relColId;
    }

    public void setRelColId(Long relColId){
        this.relColId = relColId;
    }

}
