package com.hurenjieee.entity;
// Generated 2017-3-6 18:59:56 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource",catalog = "strms")
public class Resource implements java.io.Serializable {

    private long   resId;
    private String resUuid;
    private String resName;
    private String resType;
    private Integer resState;
    private Long   resSize;
    private Long   resParId;
    private Long   resTeaId;
    private Date   resUploadTime;
    private Long   resAdmId;
    private Date   resApplyTime;

    public Resource() {}

    public Resource(long resId) {
        this.resId = resId;
    }

    public Resource(long resId, String resUuid, String resName, String resType, Long resParId, Long resTeaId, Date resUploadTime, Long resAdmId,
            Date resApplyTime) {
        this.resId = resId;
        this.resUuid = resUuid;
        this.resName = resName;
        this.resType = resType;
        this.resParId = resParId;
        this.resTeaId = resTeaId;
        this.resUploadTime = resUploadTime;
        this.resAdmId = resAdmId;
        this.resApplyTime = resApplyTime;
    }

    @Id

    @Column(name = "res_id",unique = true,nullable = false)
    public long getResId(){
        return this.resId;
    }

    public void setResId(long resId){
        this.resId = resId;
    }

    @Column(name = "res_uuid",length = 64)
    public String getResUuid(){
        return this.resUuid;
    }

    public void setResUuid(String resUuid){
        this.resUuid = resUuid;
    }

    @Column(name = "res_name")
    public String getResName(){
        return this.resName;
    }

    public void setResName(String resName){
        this.resName = resName;
    }

    @Column(name = "res_type",length = 16)
    public String getResType(){
        return this.resType;
    }

    public void setResType(String resType){
        this.resType = resType;
    }

    @Column(name = "res_par_id")
    public Long getResParId(){
        return this.resParId;
    }

    public void setResParId(Long resParId){
        this.resParId = resParId;
    }

    @Column(name = "res_tea_id")
    public Long getResTeaId(){
        return this.resTeaId;
    }

    public void setResTeaId(Long resTeaId){
        this.resTeaId = resTeaId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "res_upload_time",length = 19)
    public Date getResUploadTime(){
        return this.resUploadTime;
    }

    public void setResUploadTime(Date resUploadTime){
        this.resUploadTime = resUploadTime;
    }

    @Column(name = "res_adm_id")
    public Long getResAdmId(){
        return this.resAdmId;
    }

    public void setResAdmId(Long resAdmId){
        this.resAdmId = resAdmId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "res_apply_time",length = 19)
    public Date getResApplyTime(){
        return this.resApplyTime;
    }

    public void setResApplyTime(Date resApplyTime){
        this.resApplyTime = resApplyTime;
    }

    @Column(name = "res_size")
    public Long getResSize(){
        return resSize;
    }
    
    public void setResSize(Long resSize){
        this.resSize = resSize;
    }

    @Column(name = "res_state")
    public Integer getResState(){
        return resState;
    }
    
    public void setResState(Integer resState){
        this.resState = resState;
    }

}
