package com.hurenjieee.entity;
// Generated 2017-3-6 18:59:56 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Formula;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student",catalog = "strms")
public class Student implements java.io.Serializable {

    private long    stuId;
    private String  stuNo;
    private String  stuName;
    private String  stuPassword;
    private String  stuPicture;
    private Integer stuSex;
    private String  stuPhone;
    private String  stuEmail;
    private Long    stuColId;
    private String  stuColName;
    private String  stuBraId;
    private String  stuMajId;
    private String  stuYearId;
    private String  stuBraName;

    public Student() {}

    public Student(long stuId) {
        this.stuId = stuId;
    }

    public Student(long stuId, String stuNo, String stuName, String stuPicture, Integer stuSex, String stuPhone, String stuEmail, Long stuColId) {
        this.stuId = stuId;
        this.stuNo = stuNo;
        this.stuName = stuName;
        this.stuPicture = stuPicture;
        this.stuSex = stuSex;
        this.stuPhone = stuPhone;
        this.stuEmail = stuEmail;
        this.stuColId = stuColId;
    }

    @Id

    @Column(name = "stu_id",unique = true,nullable = false)
    public long getStuId(){
        return this.stuId;
    }

    public void setStuId(long stuId){
        this.stuId = stuId;
    }

    @Column(name = "stu_no",length = 16)
    public String getStuNo(){
        return this.stuNo;
    }

    public void setStuNo(String stuNo){
        this.stuNo = stuNo;
    }

    @Column(name = "stu_name",length = 16)
    public String getStuName(){
        return this.stuName;
    }

    public void setStuName(String stuName){
        this.stuName = stuName;
    }

    @Column(name = "stu_password",length = 64)
    public String getStuPassword(){
        return stuPassword;
    }
    
    public void setStuPassword(String stuPassword){
        this.stuPassword = stuPassword;
    }

    @Column(name = "stu_picture",length = 64)
    public String getStuPicture(){
        return this.stuPicture;
    }

    public void setStuPicture(String stuPicture){
        this.stuPicture = stuPicture;
    }

    @Column(name = "stu_sex")
    public Integer getStuSex(){
        return this.stuSex;
    }

    public void setStuSex(Integer stuSex){
        this.stuSex = stuSex;
    }

    @Column(name = "stu_phone",length = 16)
    public String getStuPhone(){
        return this.stuPhone;
    }

    public void setStuPhone(String stuPhone){
        this.stuPhone = stuPhone;
    }

    @Column(name = "stu_email",length = 32)
    public String getStuEmail(){
        return this.stuEmail;
    }

    public void setStuEmail(String stuEmail){
        this.stuEmail = stuEmail;
    }

    @Column(name = "stu_col_id")
    public Long getStuColId(){
        return this.stuColId;
    }

    public void setStuColId(Long stuColId){
        this.stuColId = stuColId;
    }

    @Formula("(select c.col_name  from collective c where c.col_id = stu_col_id)") 
    public String getStuColName(){
        return stuColName;
    }
    
    public void setStuColName(String stuColName){
        this.stuColName = stuColName;
    }

    @Formula("(select b.bra_id "
            + "from branch b "
            + "left join major m on b.bra_id = m.maj_bra_id "
            + "left join collective c on m.maj_id = c.col_maj_id "
            + "where c.col_id = stu_col_id)") 
    public String getStuBraId(){
        return stuBraId;
    }

    
    public void setStuBraId(String stuBraId){
        this.stuBraId = stuBraId;
    }

    @Formula("(select m.maj_id "
            + "from major m "
            + "left join collective c on m.maj_id = c.col_maj_id "
            + "where c.col_id = stu_col_id)") 
    public String getStuMajId(){
        return stuMajId;
    }

    
    public void setStuMajId(String stuMajId){
        this.stuMajId = stuMajId;
    }

    @Formula("(select c.col_year  from collective c where c.col_id = stu_col_id)") 
    public String getStuYearId(){
        return stuYearId;
    }

    
    public void setStuYearId(String stuYearId){
        this.stuYearId = stuYearId;
    }

    @Formula("(select b.bra_name "
            + "from branch b "
            + "left join major m on b.bra_id = m.maj_bra_id "
            + "left join collective c on m.maj_id = c.col_maj_id "
            + "where c.col_id = stu_col_id)") 
    public String getStuBraName(){
        return stuBraName;
    }

    
    public void setStuBraName(String stuBraName){
        this.stuBraName = stuBraName;
    }

}
