package com.hurenjieee.entity;
// Generated 2017-3-6 18:59:56 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student",catalog = "strms")
public class Student implements java.io.Serializable {

    private long    stuId;
    private String  stuNo;
    private String  stuName;
    private String  stuPicture;
    private Integer stuSex;
    private String  stuPhone;
    private String  stuMail;
    private Long    stuColId;

    public Student() {}

    public Student(long stuId) {
        this.stuId = stuId;
    }

    public Student(long stuId, String stuNo, String stuName, String stuPicture, Integer stuSex, String stuPhone, String stuMail, Long stuColId) {
        this.stuId = stuId;
        this.stuNo = stuNo;
        this.stuName = stuName;
        this.stuPicture = stuPicture;
        this.stuSex = stuSex;
        this.stuPhone = stuPhone;
        this.stuMail = stuMail;
        this.stuColId = stuColId;
    }

    @Id

    @Column(name = "stu_id",unique = true,nullable = false)
    public long getStuId(){
        return this.stuId;
    }

    public void setStuId(long stuId){
        this.stuId = stuId;
    }

    @Column(name = "stu_no",length = 16)
    public String getStuNo(){
        return this.stuNo;
    }

    public void setStuNo(String stuNo){
        this.stuNo = stuNo;
    }

    @Column(name = "stu_name",length = 16)
    public String getStuName(){
        return this.stuName;
    }

    public void setStuName(String stuName){
        this.stuName = stuName;
    }

    @Column(name = "stu_picture",length = 64)
    public String getStuPicture(){
        return this.stuPicture;
    }

    public void setStuPicture(String stuPicture){
        this.stuPicture = stuPicture;
    }

    @Column(name = "stu_sex")
    public Integer getStuSex(){
        return this.stuSex;
    }

    public void setStuSex(Integer stuSex){
        this.stuSex = stuSex;
    }

    @Column(name = "stu_phone",length = 16)
    public String getStuPhone(){
        return this.stuPhone;
    }

    public void setStuPhone(String stuPhone){
        this.stuPhone = stuPhone;
    }

    @Column(name = "stu_mail",length = 32)
    public String getStuMail(){
        return this.stuMail;
    }

    public void setStuMail(String stuMail){
        this.stuMail = stuMail;
    }

    @Column(name = "stu_col_id")
    public Long getStuColId(){
        return this.stuColId;
    }

    public void setStuColId(Long stuColId){
        this.stuColId = stuColId;
    }

}
