package com.hurenjieee.entity;
// Generated 2016-12-13 14:41:12 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "strms")
public class Student implements java.io.Serializable {

	private int stuUuid;
	private Collective collective;
	private String stuNo;
	private String stuName;
	private String stuPassword;
	private String stuPic;
	private String stuSex;

	public Student() {
	}

	public Student(int stuUuid) {
		this.stuUuid = stuUuid;
	}

	public Student(int stuUuid, Collective collective, String stuNo, String stuName, String stuPassword, String stuPic,
			String stuSex) {
		this.stuUuid = stuUuid;
		this.collective = collective;
		this.stuNo = stuNo;
		this.stuName = stuName;
		this.stuPassword = stuPassword;
		this.stuPic = stuPic;
		this.stuSex = stuSex;
	}

	@Id

	@Column(name = "stu_uuid", unique = true, nullable = false)
	public int getStuUuid() {
		return this.stuUuid;
	}

	public void setStuUuid(int stuUuid) {
		this.stuUuid = stuUuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stu_col_uuid")
	public Collective getCollective() {
		return this.collective;
	}

	public void setCollective(Collective collective) {
		this.collective = collective;
	}

	@Column(name = "stu_no")
	public String getStuNo() {
		return this.stuNo;
	}

	public void setStuNo(String stuNo) {
		this.stuNo = stuNo;
	}

	@Column(name = "stu_name")
	public String getStuName() {
		return this.stuName;
	}

	public void setStuName(String stuName) {
		this.stuName = stuName;
	}

	@Column(name = "stu_password")
	public String getStuPassword() {
		return this.stuPassword;
	}

	public void setStuPassword(String stuPassword) {
		this.stuPassword = stuPassword;
	}

	@Column(name = "stu_pic")
	public String getStuPic() {
		return this.stuPic;
	}

	public void setStuPic(String stuPic) {
		this.stuPic = stuPic;
	}

	@Column(name = "stu_sex")
	public String getStuSex() {
		return this.stuSex;
	}

	public void setStuSex(String stuSex) {
		this.stuSex = stuSex;
	}

}
