package com.hurenjieee.entity;
// Generated 2016-12-12 22:04:30 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "strms")
public class Teacher implements java.io.Serializable {

	private int teaUuid;
	private Major major;
	private String teaName;
	private String teaPassword;
	private String teaQua;
	private String teaPic;
	private String teaDes;
	private String teaAge;

	public Teacher() {
	}

	public Teacher(int teaUuid) {
		this.teaUuid = teaUuid;
	}

	public Teacher(int teaUuid, Major major, String teaName, String teaPassword, String teaQua, String teaPic,
			String teaDes, String teaAge) {
		this.teaUuid = teaUuid;
		this.major = major;
		this.teaName = teaName;
		this.teaPassword = teaPassword;
		this.teaQua = teaQua;
		this.teaPic = teaPic;
		this.teaDes = teaDes;
		this.teaAge = teaAge;
	}

	@Id

	@Column(name = "tea_uuid", unique = true, nullable = false)
	public int getTeaUuid() {
		return this.teaUuid;
	}

	public void setTeaUuid(int teaUuid) {
		this.teaUuid = teaUuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tea_maj_uuid")
	public Major getMajor() {
		return this.major;
	}

	public void setMajor(Major major) {
		this.major = major;
	}

	@Column(name = "tea_name")
	public String getTeaName() {
		return this.teaName;
	}

	public void setTeaName(String teaName) {
		this.teaName = teaName;
	}

	@Column(name = "tea_password")
	public String getTeaPassword() {
		return this.teaPassword;
	}

	public void setTeaPassword(String teaPassword) {
		this.teaPassword = teaPassword;
	}

	@Column(name = "tea_qua")
	public String getTeaQua() {
		return this.teaQua;
	}

	public void setTeaQua(String teaQua) {
		this.teaQua = teaQua;
	}

	@Column(name = "tea_pic")
	public String getTeaPic() {
		return this.teaPic;
	}

	public void setTeaPic(String teaPic) {
		this.teaPic = teaPic;
	}

	@Column(name = "tea_des")
	public String getTeaDes() {
		return this.teaDes;
	}

	public void setTeaDes(String teaDes) {
		this.teaDes = teaDes;
	}

	@Column(name = "tea_age")
	public String getTeaAge() {
		return this.teaAge;
	}

	public void setTeaAge(String teaAge) {
		this.teaAge = teaAge;
	}

}
