package com.hurenjieee.entity;
// Generated 2016-12-23 22:59:09 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "strms")
public class Teacher implements java.io.Serializable {

	private int teaUuid;
	private String teaName;
	private String teaPassword;
	private String teaQua;
	private String teaPic;
	private String teaDes;
	private String teaAge;
	private String teaMajUuid;

	public Teacher() {
	}

	public Teacher(int teaUuid) {
		this.teaUuid = teaUuid;
	}

	public Teacher(int teaUuid, String teaName, String teaPassword, String teaQua, String teaPic, String teaDes,
			String teaAge, String teaMajUuid) {
		this.teaUuid = teaUuid;
		this.teaName = teaName;
		this.teaPassword = teaPassword;
		this.teaQua = teaQua;
		this.teaPic = teaPic;
		this.teaDes = teaDes;
		this.teaAge = teaAge;
		this.teaMajUuid = teaMajUuid;
	}

	@Id

	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid.hex")
	@Column(name = "tea_uuid", unique = true, nullable = false)
	public int getTeaUuid() {
		return this.teaUuid;
	}

	public void setTeaUuid(int teaUuid) {
		this.teaUuid = teaUuid;
	}

	@Column(name = "tea_name")
	public String getTeaName() {
		return this.teaName;
	}

	public void setTeaName(String teaName) {
		this.teaName = teaName;
	}

	@Column(name = "tea_password")
	public String getTeaPassword() {
		return this.teaPassword;
	}

	public void setTeaPassword(String teaPassword) {
		this.teaPassword = teaPassword;
	}

	@Column(name = "tea_qua")
	public String getTeaQua() {
		return this.teaQua;
	}

	public void setTeaQua(String teaQua) {
		this.teaQua = teaQua;
	}

	@Column(name = "tea_pic")
	public String getTeaPic() {
		return this.teaPic;
	}

	public void setTeaPic(String teaPic) {
		this.teaPic = teaPic;
	}

	@Column(name = "tea_des")
	public String getTeaDes() {
		return this.teaDes;
	}

	public void setTeaDes(String teaDes) {
		this.teaDes = teaDes;
	}

	@Column(name = "tea_age")
	public String getTeaAge() {
		return this.teaAge;
	}

	public void setTeaAge(String teaAge) {
		this.teaAge = teaAge;
	}

	@Column(name = "tea_maj_uuid", length = 32)
	public String getTeaMajUuid() {
		return this.teaMajUuid;
	}

	public void setTeaMajUuid(String teaMajUuid) {
		this.teaMajUuid = teaMajUuid;
	}

}
