package com.hurenjieee.entity;
// Generated 2017-3-6 18:59:56 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Formula;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher",catalog = "strms")
public class Teacher implements java.io.Serializable {

    private long    teaId;
    private String  teaNo;
    private String  teaName;
    private String  teaPassword;
    private String  teaPicture;
    private String  teaEmail;
    private String  teaPhone;
    private Integer teaLevel;
    private String  teaDescription;
    private Long    teaBraId;
    private String  teaBraName;

    public Teacher() {}

    public Teacher(long teaId) {
        this.teaId = teaId;
    }

    public Teacher(long teaId, String teaNo, String teaName, String teaPassword, String teaPicture, String teaEmail, String teaPhone, Integer teaLevel,
            String teaDescription, Long teaBraId) {
        this.teaId = teaId;
        this.teaNo = teaNo;
        this.teaName = teaName;
        this.teaPassword = teaPassword;
        this.teaPicture = teaPicture;
        this.teaEmail = teaEmail;
        this.teaPhone = teaPhone;
        this.teaLevel = teaLevel;
        this.teaDescription = teaDescription;
        this.teaBraId = teaBraId;
    }

    @Id

    @Column(name = "tea_id",unique = true,nullable = false)
    public long getTeaId(){
        return this.teaId;
    }

    public void setTeaId(long teaId){
        this.teaId = teaId;
    }

    @Column(name = "tea_no",length = 16)
    public String getTeaNo(){
        return this.teaNo;
    }

    public void setTeaNo(String teaNo){
        this.teaNo = teaNo;
    }

    @Column(name = "tea_name",length = 16)
    public String getTeaName(){
        return this.teaName;
    }

    public void setTeaName(String teaName){
        this.teaName = teaName;
    }

    @Column(name = "tea_password",length = 64)
    public String getTeaPassword(){
        return this.teaPassword;
    }

    public void setTeaPassword(String teaPassword){
        this.teaPassword = teaPassword;
    }

    @Column(name = "tea_picture",length = 64)
    public String getTeaPicture(){
        return this.teaPicture;
    }

    public void setTeaPicture(String teaPicture){
        this.teaPicture = teaPicture;
    }

    @Column(name = "tea_email",length = 32)
    public String getTeaEmail(){
        return this.teaEmail;
    }

    public void setTeaEmail(String teaEmail){
        this.teaEmail = teaEmail;
    }

    @Column(name = "tea_phone",length = 16)
    public String getTeaPhone(){
        return this.teaPhone;
    }

    public void setTeaPhone(String teaPhone){
        this.teaPhone = teaPhone;
    }

    @Column(name = "tea_level")
    public Integer getTeaLevel(){
        return this.teaLevel;
    }

    public void setTeaLevel(Integer teaLevel){
        this.teaLevel = teaLevel;
    }

    @Column(name = "tea_description",length = 1024)
    public String getTeaDescription(){
        return this.teaDescription;
    }

    public void setTeaDescription(String teaDescription){
        this.teaDescription = teaDescription;
    }

    @Column(name = "tea_bra_id")
    public Long getTeaBraId(){
        return this.teaBraId;
    }

    public void setTeaBraId(Long teaBraId){
        this.teaBraId = teaBraId;
    }

    @Formula("(select b.bra_name  from branch b where b.bra_id = tea_bra_id)") 
    public String getTeaBraName(){
        return teaBraName;
    }
    
    public void setTeaBraName(String teaBraName){
        this.teaBraName = teaBraName;
    }

}
