package com.hurenjieee.entity;
// Generated 2016-12-23 22:59:09 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Userr generated by hbm2java
 */
@Entity
@Table(name = "userr", catalog = "strms")
public class Userr  implements java.io.Serializable{

	private String uuid;
	private Integer userId;
	private String passWord;
	private String userName;

	public Userr() {
	}

	public Userr(String uuid) {
		this.uuid = uuid;
	}

	public Userr(String uuid, Integer userId, String passWord, String userName) {
		this.uuid = uuid;
		this.userId = userId;
		this.passWord = passWord;
		this.userName = userName;
	}

	@Id

	@Column(name = "uuid", unique = true, nullable = false)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "passWord")
	public String getPassWord() {
		return this.passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	@Column(name = "userName")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
